export const ALL_QUESTIONS = [
    {
        id: 'situation-current',
        category: { en: 'Current Situation', fr: 'Situation Actuelle', es: 'Situación Actual', de: 'Aktuelle Situation', it: 'Situazione Attuale' },
        text: {
            en: "What occupies your mind and time the most at this exact moment?",
            fr: "Qu'est-ce qui occupe le plus clair de ton esprit et de ton temps en ce moment précis ?",
            es: "¿Qué ocupa la mayor parte de tu mente y tiempo en este preciso momento?",
            de: "Was beschäftigt Ihren Geist und Ihre Zeit in diesem genau Moment am meisten?",
            it: "Cosa occupa la maggior parte della tua mente e del tuo tempo in questo momento esatto?"
        },
        defaultSelected: true
    },
    {
        id: 'family-friends',
        category: { en: 'Family & Friends', fr: 'Amis & Famille', es: 'Familia y Amigos', de: 'Familie & Freunde', it: 'Famiglia e Amici' },
        text: {
            en: "Which relationship or shared moment with a loved one has recently stood out to you?",
            fr: "Quelle relation ou quel moment partagé avec un proche t'a particulièrement marqué ces derniers temps ?",
            es: "¿Qué relación o momento compartido con un ser querido te ha marcado recientemente?",
            de: "Welche Beziehung oder welcher geteilte Moment mit einem geliebten Menschen hat Sie in letzter Zeit besonders berührt?",
            it: "Quale relazione o momento condiviso con una persona cara ti ha colpito particolarmente di recente?"
        },
        defaultSelected: true
    },
    {
        id: 'life-desire',
        category: { en: 'Life & Ambitions', fr: 'Désir de Vie', es: 'Deseos de Vida', de: 'Lebenswünsche', it: 'Desideri di Vita' },
        text: {
            en: "If you could achieve a major project or radically change a habit in the coming months, what would it be?",
            fr: "Si tu pouvais réaliser un grand projet ou changer radicalement une habitude dans les mois à venir, ce serait quoi ?",
            es: "Si pudieras lograr un gran proyecto o cambiar radicalmente un hábito en los próximos meses, ¿cuál sería?",
            de: "Wenn Sie in den kommenden Monaten ein großes Projekt verwirklichen oder eine Gewohnheit radikal ändern könnten, was wäre das?",
            it: "Se potessi realizzare un grande progetto o cambiare radicalmente un'abitudine nei prossimi mesi, quale sarebbe?"
        },
        defaultSelected: true
    },
    {
        id: 'future-learning',
        category: { en: 'Future & Learning', fr: 'Apprentissage Futur', es: 'Futuro y Aprendizaje', de: 'Zukunft & Lernen', it: 'Futuro e Apprendimento' },
        text: {
            en: "What skill or knowledge would you absolutely love to acquire or master in the future?",
            fr: "Quelle compétence ou quelle connaissance aimerais-tu absolument acquérir ou maîtriser dans le futur ?",
            es: "¿Qué habilidad o conocimiento te encantaría adquirir o dominar absolutamente en el futuro?",
            de: "Welche Fähigkeit oder welches Wissen würden Sie in Zukunft unbedingt gerne erwerben oder meistern?",
            it: "Quale abilità o conoscenza ti piacerebbe assolutamente acquisire o padroneggiare in futuro?"
        },
        defaultSelected: true
    },
    {
        id: 'worldwide-situation',
        category: { en: 'Worldview', fr: 'Situation Mondiale', es: 'Situación Mundial', de: 'Weltgeschehen', it: 'Situazione Mondiale' },
        text: {
            en: "What is your current perspective on the state of the world today and its direction?",
            fr: "Quel regard portes-tu sur l'état du monde actuel et son évolution ?",
            es: "¿Cuál es tu perspectiva actual sobre el estado del mundo de hoy y su dirección?",
            de: "Wie blicken Sie auf den Zustand der heutigen Welt und ihre Entwicklung?",
            it: "Qual è la tua attuale prospettiva sullo stato del mondo oggi e sulla sua direzione?"
        },
        defaultSelected: true
    },
    {
        id: 'career-milestone',
        category: { en: 'Career & Projects', fr: 'Carrière & Projets', es: 'Carrera y Proyectos', de: 'Karriere & Projekte', it: 'Carriera e Progetti' },
        text: {
            en: "How do you feel about your current professional trajectory or main creative projects right now?",
            fr: "Comment te sens-tu par rapport à ta trajectoire professionnelle actuelle ou tes principaux projets créatifs ?",
            es: "¿Cómo te sientes acerca de tu actual trayectoria profesional o tus principales proyectos creativos?",
            de: "Wie empfinden Sie Ihre aktuelle berufliche Laufbahn oder Ihre wichtigsten kreativen Projekte?",
            it: "Come ti senti riguardo alla tua attuale traiettoria professionale o ai tuoi principali progetti creativi?"
        },
        defaultSelected: false
    },
    {
        id: 'personal-growth',
        category: { en: 'Personal Growth', fr: 'Évolution Personnelle', es: 'Crecimiento Personal', de: 'Persönliches Wachstum', it: 'Crescita Personale' },
        text: {
            en: "What is the most important personal lesson or realization you have experienced recently?",
            fr: "Quelle est la leçon ou prise de conscience personnelle la plus importante que tu as vécue récemment ?",
            es: "¿Cuál es la lección o toma de conciencia personal más importante que has experimentado recientemente?",
            de: "Was ist die wichtigste persönliche Erkenntnis, die Sie in letzter Zeit gemacht haben?",
            it: "Qual è la lezione o la realizzazione personale più importante che hai vissuto di recente?"
        },
        defaultSelected: false
    },
    {
        id: 'health-energy',
        category: { en: 'Health & Well-being', fr: 'Santé & Énergie', es: 'Salud y Bienestar', de: 'Gesundheit & Wohlbefinden', it: 'Salute e Benessere' },
        text: {
            en: "How are you managing your physical energy, mental balance, and daily well-being right now?",
            fr: "Comment gères-tu ton énergie physique, ton équilibre mental et ton bien-être au quotidien en ce moment ?",
            es: "¿Cómo estás gestionando tu energía física, tu equilibrio mental y tu bienestar diario en este momento?",
            de: "Wie managen Sie im Moment Ihre körperliche Energie, Ihre mentale Balance und Ihr tägliches Wohlbefinden?",
            it: "Come stai gestendo la tua energia fisica, il tuo equilibrio mentale e il tuo benessere quotidiano in questo momento?"
        },
        defaultSelected: false
    },
    {
        id: 'five-year-vision',
        category: { en: 'Vision', fr: 'Vision à 5 ans', es: 'Visión a 5 años', de: '5-Jahres-Vision', it: 'Visione a 5 anni' },
        text: {
            en: "Looking ahead, where do you realistically see yourself living, working, and thriving in 5 years?",
            fr: "En se projetant, où te vois-tu de manière réaliste vivre, travailler et t'épanouir d'ici 5 ans ?",
            es: "Mirando hacia adelante, ¿dónde te ves realistamente viviendo, trabajando y prosperando en 5 años?",
            de: "Wenn Sie nach vorne blicken: Wo sehen Sie sich in 5 Jahren realistischerweise leben, arbeiten und gedeihen?",
            it: "Guardando avanti, dove ti vedi realisticamente a vivere, lavorare e prosperare tra 5 anni?"
        },
        defaultSelected: false
    },
    {
        id: 'gratitude-joy',
        category: { en: 'Gratitude', fr: 'Gratitude & Joie', es: 'Gratitud y Alegría', de: 'Dankbarkeit & Freude', it: 'Gratitudine e Gioia' },
        text: {
            en: "What small or simple things brought you the most joy or gratitude over the past few months?",
            fr: "Quelles petites ou simples choses t'ont apporté le plus de joie ou de gratitude au cours des derniers mois ?",
            es: "¿Qué pequeñas o simples cosas te han traído más alegría o gratitud en los últimos meses?",
            de: "Welche kleinen oder einfachen Dinge haben Ihnen in den letzten Monaten die meiste Freude oder Dankbarkeit gebracht?",
            it: "Quali piccole o semplici cose ti hanno dato più gioia o gratitudine negli ultimi mesi?"
        },
        defaultSelected: false
    }
];

export const TRANSLATIONS = {
    en: {
        appName: "VideoLog",
        manifestoTitle: "Your Personal Time Capsule",
        manifestoText: "Life moves fast. Perspectives shift, ambitions evolve, and memories blur. VideoLog is your private space to pause every 6 months—capturing your raw mindset, your current challenges, and your vision of the world. In a few years, your future self will thank you for preserving who you were today.",
        recordSession: "Record Session",
        recordSubtitle: "Answer your 5 active questions one by one.",
        startRecording: "Start Recording Session",
        importFolder: "Scan / Import from Folder",
        importedCount: "imported successfully!",
        recordedSessions: "Recorded Sessions",
        noSessions: "No videologs recorded yet. Start your first session above or import existing files!",
        play: "Play",
        dashboard: "Dashboard",
        settings: "Settings",
        about: "About",
        settingsTitle: "Settings & Question Selection",
        usernameLabel: "Your Name / Username",
        usernameHint: "Used in downloaded video filenames.",
        usernameRequired: "Please enter your name to continue.",
        languageLabel: "Language",
        activeQuestionsLabel: "Active Questions (Max 5)",
        editQuestionsTitle: "Manage Your 5 Active Questions",
        addQuestion: "Add",
        remove: "Remove",
        remindersTitle: "Reminders",
        remindersText: "Download an ICS reminder file for recurring 6-month check-ins.",
        downloadICS: "Download 6-Month Reminder (.ics)",
        cancel: "Dashboard",
        recordAnswer: "Record Answer",
        finishSave: "Finish & Save",
        updateAvailable: "Update Available",
        updateText: "A new version of VideoLog has been released. Refresh now to get the latest features and fixes.",
        later: "Later",
        refreshNow: "Refresh Now",
        installAppTitle: "Install VideoLog",
        installAppText: "Install VideoLog on your device for quick access, offline recording, and a native app experience.",
        installNow: "Install App",
        notNow: "Not Now",
        sessionComplete: "Session complete! All answers recorded and saved locally.",
        onboardingTitle: "Welcome to VideoLog",
        onboardingSubtitle: "Choose up to 5 questions that matter most to you for your time capsule sessions.",
        skipOnboarding: "Skip & Use Default (5)",
        saveOnboarding: "Save & Start Using VideoLog",
        selectedCount: "Selected",
        aboutTitle: "About VideoLog",
        aboutLocal: "100% local — your data never leaves this device unless you choose to back it up.",
        aboutWhatTitle: "What is VideoLog?",
        aboutWhatText: "VideoLog is a private time capsule on your device. A couple of times a year, you record a short video of yourself answering a few personal questions. Years later, look back and see exactly who you were - your hopes, your worries, your voice. It is your story, kept safe and private.",
        aboutFaqTitle: "Your questions about privacy",
        aboutFaqLead: "In simple words:",
        aboutQ1: "Where are my videos kept?",
        aboutA1: "On your own device, in this app's private storage. They stay there and go nowhere unless you decide to move them.",
        aboutQ2: "Is my data sent to a server?",
        aboutA2: "No. The app runs entirely on your device. Nothing is uploaded automatically, ever.",
        aboutQ3: "Then what is the cloud backup for?",
        aboutA3: "If you want an extra copy, you can press the backup button on a video to send it to your own Google Drive or Dropbox account, in a VideoLog folder. This is always your choice and never automatic.",
        aboutQ4: "Do you use my camera or microphone?",
        aboutA4: "Only while you are recording, and only to make your video. As soon as you stop, they are released. Nothing is captured when you are not recording.",
        aboutQ5: "Do you track me or show ads?",
        aboutA5: "No. There is no tracking, no analytics, no ads, and no account required. The app also works fully offline.",
        aboutQ6: "Can I delete my videos?",
        aboutA6: "Yes. Tap the delete button on any video and it is removed from the app. Note: the original video file may still be in your folder if you saved it there."
    },
    fr: {
        appName: "VideoLog",
        manifestoTitle: "Votre Capsule Temporelle Personnelle",
        manifestoText: "La vie va vite. Les perspectives changent, les ambitions évoluent et les souvenirs s'estompent. VideoLog est votre espace privé pour faire une pause tous les 6 mois : capturez votre état d'esprit brut, vos défis actuels et votre vision du monde. Dans quelques ans, votre futur vous remerciera d'avoir préservé qui vous étiez aujourd'hui.",
        recordSession: "Enregistrer une session",
        recordSubtitle: "Répondez à vos 5 questions actives une par une.",
        startRecording: "Démarrer la session d'enregistrement",
        importFolder: "Scanner / Importer un dossier",
        importedCount: "importés avec succès !",
        recordedSessions: "Sessions enregistrées",
        noSessions: "Aucun videolog pour l'instant. Démarrez votre première session ci-dessus ou importez des fichiers existants !",
        play: "Lire",
        dashboard: "Tableau de bord",
        settings: "Paramètres",
        about: "À propos",
        settingsTitle: "Paramètres & Sélection des questions",
        usernameLabel: "Votre Nom / Pseudo",
        usernameHint: "Utilisé dans les noms de fichiers vidéo téléchargés.",
        usernameRequired: "Veuillez saisir votre nom pour continuer.",
        languageLabel: "Langue",
        activeQuestionsLabel: "Questions Actives (Max 5)",
        editQuestionsTitle: "Gérer vos 5 questions actives",
        addQuestion: "Ajouter",
        remove: "Retirer",
        remindersTitle: "Rappels",
        remindersText: "Téléchargez un fichier ICS pour configurer un rappel récurrent tous les 6 mois.",
        downloadICS: "Télécharger le rappel 6 mois (.ics)",
        cancel: "Tableau de bord",
        recordAnswer: "Enregistrer la réponse",
        finishSave: "Terminer & Sauvegarder",
        updateAvailable: "Mise à jour disponible",
        updateText: "Une nouvelle version de VideoLog est sortie. Actualisez pour obtenir les dernières fonctionnalités.",
        later: "Plus tard",
        refreshNow: "Actualiser",
        installAppTitle: "Installer VideoLog",
        installAppText: "Installez VideoLog sur votre appareil pour un accès rapide, un enregistrement hors-ligne et une expérience native.",
        installNow: "Installer",
        notNow: "Pas maintenant",
        sessionComplete: "Session terminée ! Toutes les réponses ont été enregistrées localement.",
        onboardingTitle: "Bienvenue sur VideoLog",
        onboardingSubtitle: "Choisissez jusqu'à 5 questions qui comptent le plus pour vous lors de vos sessions de capsule temporelle.",
        skipOnboarding: "Passer (utiliser les 5 par défaut)",
        saveOnboarding: "Enregistrer & Démarrer",
        selectedCount: "Sélectionnées",
        aboutTitle: "À propos de VideoLog",
        aboutLocal: "100 % local — vos données ne quittent jamais cet appareil sauf si vous choisissez de les sauvegarder.",
        aboutWhatTitle: "Qu'est-ce que VideoLog ?",
        aboutWhatText: "VideoLog est une capsule temporelle privée sur votre appareil. Deux fois par an environ, vous enregistrez une courte vidéo de vous en répondant à quelques questions personnelles. Des années plus tard, regardez en arrière et voyez exactement qui vous étiez : vos espoirs, vos inquiétudes, votre voix. C'est votre histoire, conservée en toute sécurité et en privé.",
        aboutFaqTitle: "Vos questions sur la confidentialité",
        aboutFaqLead: "En mots simples :",
        aboutQ1: "Où sont conservées mes vidéos ?",
        aboutA1: "Sur votre propre appareil, dans l'espace de stockage privé de cette application. Elles y restent et ne vont nulle part sauf si vous décidez de les déplacer.",
        aboutQ2: "Mes données sont-elles envoyées à un serveur ?",
        aboutA2: "Non. L'application fonctionne entièrement sur votre appareil. Rien n'est téléversé automatiquement, jamais.",
        aboutQ3: "Alors à quoi sert la sauvegarde cloud ?",
        aboutA3: "Si vous voulez une copie de sécurité, vous pouvez appuyer sur le bouton de sauvegarde d'une vidéo pour l'envoyer vers votre compte Google Drive ou Dropbox, dans un dossier VideoLog. C'est toujours votre choix et jamais automatique.",
        aboutQ4: "Utilisez-vous ma caméra ou mon micro ?",
        aboutA4: "Uniquement pendant que vous enregistrez, et uniquement pour créer votre vidéo. Dès que vous arrêtez, ils sont libérés. Rien n'est capturé lorsque vous n'enregistrez pas.",
        aboutQ5: "Me suivez-vous ou affichez-vous des publicités ?",
        aboutA5: "Non. Pas de suivi, pas d'analytique, pas de publicités et aucun compte requis. L'application fonctionne aussi entièrement hors ligne.",
        aboutQ6: "Puis-je supprimer mes vidéos ?",
        aboutA6: "Oui. Appuyez sur le bouton de suppression d'une vidéo et elle est retirée de l'application. À noter : le fichier vidéo d'origine peut rester dans votre dossier si vous l'y avez enregistré."
    },
    es: {
        appName: "VideoLog",
        manifestoTitle: "Tu Cápsula del Tiempo Personal",
        manifestoText: "La vida pasa rápido. Las perspectivas cambian, las ambiciones evolucionan y los recuerdos se desvanecen. VideoLog es tu espacio privado para hacer una pausa cada 6 meses: captura tu mentalidad sin filtros, tus desafíos actuales y tu visión del mundo. En unos años, tu ‘yo’ del futuro te agradecerá por preservar quién eras hoy.",
        recordSession: "Grabar sesión",
        recordSubtitle: "Responde tus 5 preguntas activas una por una.",
        startRecording: "Iniciar sesión de grabación",
        importFolder: "Escanear / Importar carpeta",
        importedCount: "importados con éxito!",
        recordedSessions: "Sesiones grabadas",
        noSessions: "Aún no hay videologs grabados. ¡Comienza tu primera sesión arriba o importa archivos existentes!",
        play: "Reproducir",
        dashboard: "Panel",
        settings: "Ajustes",
        about: "Acerca",
        settingsTitle: "Ajustes y Selección de Preguntas",
        usernameLabel: "Tu Nombre / Usuario",
        usernameHint: "Usado en los nombres de archivos de video descargados.",
        usernameRequired: "Por favor, introduce tu nombre para continuar.",
        languageLabel: "Idioma",
        activeQuestionsLabel: "Preguntas Activas (Max 5)",
        editQuestionsTitle: "Gestionar tus 5 preguntas activas",
        addQuestion: "Añadir",
        remove: "Quitar",
        remindersTitle: "Recordatorios",
        remindersText: "Descarga un archivo ICS para configurar un recordatorio recurrente cada 6 meses.",
        downloadICS: "Descargar recordatorio de 6 meses (.ics)",
        cancel: "Panel",
        recordAnswer: "Grabar Respuesta",
        finishSave: "Terminar y Guardar",
        updateAvailable: "Actualización Disponible",
        updateText: "Se ha lanzado una nueva versión de VideoLog. Actualiza ahora para obtener las últimas mejoras.",
        later: "Más tarde",
        refreshNow: "Actualizar",
        installAppTitle: "Instalar VideoLog",
        installAppText: "Instala VideoLog en tu dispositivo para un acceso rápido, grabación offline y experiencia nativa.",
        installNow: "Instalar App",
        notNow: "Ahora no",
        sessionComplete: "¡Sesión completa! Todas las respuestas grabadas y guardadas localmente.",
        onboardingTitle: "Bienvenido a VideoLog",
        onboardingSubtitle: "Elige hasta 5 preguntas que más te importen para tus sesiones de cápsula del tiempo.",
        skipOnboarding: "Omitir (usar 5 por defecto)",
        saveOnboarding: "Guardar y Empezar",
        selectedCount: "Seleccionadas",
        aboutTitle: "Acerca de VideoLog",
        aboutLocal: "100 % local: tus datos nunca salen de este dispositivo salvo que elijas respaldarlos.",
        aboutWhatTitle: "¿Qué es VideoLog?",
        aboutWhatText: "VideoLog es una cápsula del tiempo privada en tu dispositivo. Un par de veces al año, grabas un video corto de ti respondiendo algunas preguntas personales. Años después, mira atrás y ve exactamente quién eras: tus esperanzas, tus preocupaciones, tu voz. Es tu historia, guardada segura y en privado.",
        aboutFaqTitle: "Tus preguntas sobre privacidad",
        aboutFaqLead: "En palabras sencillas:",
        aboutQ1: "¿Dónde se guardan mis videos?",
        aboutA1: "En tu propio dispositivo, en el almacenamiento privado de esta app. Se quedan ahí y no van a ningún sitio a menos que decidas moverlos.",
        aboutQ2: "¿Se envían mis datos a un servidor?",
        aboutA2: "No. La app funciona completamente en tu dispositivo. Nada se sube automáticamente, nunca.",
        aboutQ3: "Entonces, ¿para qué sirve la copia en la nube?",
        aboutA3: "Si quieres una copia extra, puedes pulsar el botón de copia de seguridad de un video para enviarlo a tu cuenta de Google Drive o Dropbox, en una carpeta VideoLog. Siempre es tu elección y nunca automático.",
        aboutQ4: "¿Usas mi cámara o micrófono?",
        aboutA4: "Solo mientras grabas, y solo para hacer tu video. En cuanto paras, se liberan. Nada se captura cuando no estás grabando.",
        aboutQ5: "¿Me rastreas o muestras anuncios?",
        aboutA5: "No. No hay seguimiento, ni análisis, ni anuncios, ni se requiere cuenta. La app también funciona totalmente sin conexión.",
        aboutQ6: "¿Puedo borrar mis videos?",
        aboutA6: "Sí. Pulsa el botón de eliminar en cualquier video y se quita de la app. Nota: el archivo de video original puede seguir en tu carpeta si lo guardaste allí."
    },
    de: {
        appName: "VideoLog",
        manifestoTitle: "Ihre persönliche Zeitkapsel",
        manifestoText: "Das Leben vergeht schnell. Perspektiven verschieben sich, Ambitionen entwickeln sich weiter und Erinnerungen verblassen. VideoLog ist Ihr privater Ort, um alle 6 Monate Innehaltet zu halten – halten Sie Ihre rohe Denkweise, Ihre aktuellen Herausforderungen und Ihre Vision der Welt fest. In ein paar Jahren wird Ihr zukünftiges Ich es Ihnen danken.",
        recordSession: "Aufnahmesitzung starten",
        recordSubtitle: "Beantworten Sie Ihre 5 aktiven Fragen nacheinander.",
        startRecording: "Aufnahme starten",
        importFolder: "Ordner scannen / importieren",
        importedCount: "erfolgreich importiert!",
        recordedSessions: "Aufgezeichnete Sitzungen",
        noSessions: "Noch keine VideoLogs vorhanden. Starten Sie Ihre erste Sitzung oben oder importieren Sie vorhandene Dateien!",
        play: "Abspielen",
        dashboard: "Übersicht",
        settings: "Einstellungen",
        about: "Über",
        settingsTitle: "Einstellungen & Fragenauswahl",
        usernameLabel: "Ihr Name / Benutzername",
        usernameHint: "Wird für heruntergeladene Videodateinamen verwendet.",
        usernameRequired: "Bitte gib deinen Namen ein, um fortzufahren.",
        languageLabel: "Sprache",
        activeQuestionsLabel: "Aktive Fragen (Max 5)",
        editQuestionsTitle: "Verwalten Sie Ihre 5 aktiven Fragen",
        addQuestion: "Hinzufügen",
        remove: "Entfernen",
        remindersTitle: "Erinnerungen",
        remindersText: "Laden Sie eine ICS-Datei für wiederkehrende 6-Monats-Erinnerungen herunter.",
        downloadICS: "6-Monats-Erinnerung herunterladen (.ics)",
        cancel: "Übersicht",
        recordAnswer: "Antwort aufnehmen",
        finishSave: "Beenden & Speichern",
        updateAvailable: "Update verfügbar",
        updateText: "Eine neue Version von VideoLog ist verfügbar. Aktualisieren Sie jetzt.",
        later: "Später",
        refreshNow: "Jetzt aktualisieren",
        installAppTitle: "VideoLog installieren",
        installAppText: "Installieren Sie VideoLog für schnellen Zugriff, Offline-Aufnahme und ein natives App-Erlebnis.",
        installNow: "App installieren",
        notNow: "Später",
        sessionComplete: "Sitzung abgeschlossen! Alle Antworten lokal gespeichert.",
        onboardingTitle: "Willkommen bei VideoLog",
        onboardingSubtitle: "Wählen Sie bis zu 5 Fragen aus, die Ihnen für Ihre Zeitkapsel-Sitzungen am wichtigsten sind.",
        skipOnboarding: "Überspringen (Standard 5 verwenden)",
        saveOnboarding: "Speichern & Starten",
        selectedCount: "Ausgewählt",
        aboutTitle: "Über VideoLog",
        aboutLocal: "100 % lokal – Ihre Daten verlassen dieses Gerät nie, es sei denn, Sie entscheiden sich für ein Backup.",
        aboutWhatTitle: "Was ist VideoLog?",
        aboutWhatText: "VideoLog ist eine private Zeitkapsel auf Ihrem Gerät. Ein paar Mal im Jahr nehmen Sie ein kurzes Video von sich auf und beantworten einige persönliche Fragen. Jahre später schauen Sie zurück und sehen genau, wer Sie waren: Ihre Hoffnungen, Ihre Sorgen, Ihre Stimme. Es ist Ihre Geschichte, sicher und privat aufbewahrt.",
        aboutFaqTitle: "Ihre Fragen zum Datenschutz",
        aboutFaqLead: "In einfachen Worten:",
        aboutQ1: "Wo werden meine Videos gespeichert?",
        aboutA1: "Auf Ihrem eigenen Gerät, im privaten Speicher dieser App. Sie bleiben dort und gehen nirgendwohin, außer Sie entscheiden sich, sie zu verschieben.",
        aboutQ2: "Werden meine Daten an einen Server gesendet?",
        aboutA2: "Nein. Die App läuft vollständig auf Ihrem Gerät. Es wird niemals automatisch etwas hochgeladen.",
        aboutQ3: "Wozu dient dann das Cloud-Backup?",
        aboutA3: "Wenn Sie eine zusätzliche Kopie möchten, können Sie den Backup-Button eines Videos drücken, um es an Ihr eigenes Google Drive- oder Dropbox-Konto zu senden, in einen VideoLog-Ordner. Das ist immer Ihre Entscheidung und niemals automatisch.",
        aboutQ4: "Nutzen Sie meine Kamera oder mein Mikrofon?",
        aboutA4: "Nur während Sie aufnehmen, und nur um Ihr Video zu erstellen. Sobald Sie stoppen, werden sie freigegeben. Es wird nichts erfasst, wenn Sie nicht aufnehmen.",
        aboutQ5: "Verfolgen Sie mich oder zeigen Sie Werbung?",
        aboutA5: "Nein. Kein Tracking, keine Analysen, keine Werbung und kein Konto erforderlich. Die App funktioniert auch vollständig offline.",
        aboutQ6: "Kann ich meine Videos löschen?",
        aboutA6: "Ja. Tippen Sie auf den Löschen-Button eines Videos, und es wird aus der App entfernt. Hinweis: Die Originalvideodatei kann weiterhin in Ihrem Ordner liegen, wenn Sie sie dort gespeichert haben."
    },
    it: {
        appName: "VideoLog",
        manifestoTitle: "La tua Capsula del Tempo Personale",
        manifestoText: "La vita scorre veloce. Le prospettive cambiano, le ambizioni evolvono e i ricordi sfumano. VideoLog è il tuo spazio privato per fermarti ogni 6 mesi: cattura la tua mentalità autentica, le tue sfide attuali e la tua visione del mondo. Tra qualche anno, il tuo io futuro ti ringrazierà per aver preservato chi eri oggi.",
        recordSession: "Avvia sessione di registrazione",
        recordSubtitle: "Rispondi alle tue 5 domande attive una per una.",
        startRecording: "Avvia registrazione",
        importFolder: "Scansiona / Importa cartella",
        importedCount: "importati con successo!",
        recordedSessions: "Sessioni registrate",
        noSessions: "Nessun videolog registrato. Inizia la tua prima sessione qui sopra o importa file esistenti!",
        play: "Riproduci",
        dashboard: "Dashboard",
        settings: "Impostazioni",
        about: "Info",
        settingsTitle: "Impostazioni e Selezione Domande",
        usernameLabel: "Il tuo Nome / Username",
        usernameHint: "Utilizzato nei nomi dei file video scaricati.",
        usernameRequired: "Inserisci il tuo nome per continuare.",
        languageLabel: "Lingua",
        activeQuestionsLabel: "Domande Attive (Max 5)",
        editQuestionsTitle: "Gestisci le tue 5 domande attive",
        addQuestion: "Aggiungi",
        remove: "Rimuovi",
        remindersTitle: "Promemoria",
        remindersText: "Scarica un file ICS per impostare un promemoria ricorrente ogni 6 mesi.",
        downloadICS: "Scarica Promemoria 6 Mesi (.ics)",
        cancel: "Dashboard",
        recordAnswer: "Registra Risposta",
        finishSave: "Termina e Salva",
        updateAvailable: "Aggiornamento Disponibile",
        updateText: "È stata rilasciata una nuova versione di VideoLog. Aggiorna ora per le ultime novità.",
        later: "Più tardi",
        refreshNow: "Aggiorna Ora",
        installAppTitle: "Installa VideoLog",
        installAppText: "Installa VideoLog sul tuo dispositivo per un accesso rapido, registrazione offline ed esperienza nativa.",
        installNow: "Installa App",
        notNow: "Non ora",
        sessionComplete: "Sessione completata! Tutte le risposte registrate e salvate localmente.",
        onboardingTitle: "Benvenuto su VideoLog",
        onboardingSubtitle: "Scegli fino a 5 domande che contano di più per te per le tue sessioni di capsula del tempo.",
        skipOnboarding: "Salta (usa le 5 di default)",
        saveOnboarding: "Salva e Inizia",
        selectedCount: "Selezionate",
        aboutTitle: "Informazioni su VideoLog",
        aboutLocal: "100% locale: i tuoi dati non lasciano mai questo dispositivo a meno che tu non scelga di farne un backup.",
        aboutWhatTitle: "Cos'è VideoLog?",
        aboutWhatText: "VideoLog è una capsula del tempo privata sul tuo dispositivo. Un paio di volte all'anno, registri un breve video di te rispondendo ad alcune domande personali. Anni dopo, guarda indietro e vedi esattamente chi eri: le tue speranze, le tue preoccupazioni, la tua voce. È la tua storia, custodita al sicuro e in privato.",
        aboutFaqTitle: "Le tue domande sulla privacy",
        aboutFaqLead: "In parole semplici:",
        aboutQ1: "Dove vengono conservati i miei video?",
        aboutA1: "Sul tuo dispositivo, nello spazio di archiviazione privato di questa app. Restano lì e non vanno da nessuna parte a meno che tu non decida di spostarli.",
        aboutQ2: "I miei dati vengono inviati a un server?",
        aboutA2: "No. L'app funziona interamente sul tuo dispositivo. Non viene mai caricato nulla automaticamente.",
        aboutQ3: "Allora a cosa serve il backup cloud?",
        aboutA3: "Se vuoi una copia extra, puoi premere il pulsante di backup di un video per inviarlo al tuo account Google Drive o Dropbox, in una cartella VideoLog. È sempre una tua scelta e mai automatica.",
        aboutQ4: "Usi la mia fotocamera o il microfono?",
        aboutA4: "Solo mentre registri, e solo per creare il tuo video. Appena ti fermi, vengono rilasciati. Non viene catturato nulla quando non stai registrando.",
        aboutQ5: "Mi tracci o mostri pubblicità?",
        aboutA5: "No. Nessun tracciamento, nessuna analisi, nessuna pubblicità e nessun account richiesto. L'app funziona anche completamente offline.",
        aboutQ6: "Posso eliminare i miei video?",
        aboutA6: "Sì. Premi il pulsante di eliminazione su qualsiasi video e verrà rimosso dall'app. Nota: il file video originale potrebbe restare nella tua cartella se lo hai salvato lì."
    }
};
