export const ALL_QUESTIONS = [
    {
        id: 'situation-current',
        category: { en: 'Current Situation', fr: 'Situation Actuelle', es: 'Situación Actual', de: 'Aktuelle Situation', it: 'Situazione Attuale' },
        text: {
            en: "What occupies your mind and time the most at this exact moment?",
            fr: "Qu'est-ce qui occupe le plus clair de ton esprit et de ton temps en ce moment précis ?",
            es: "¿Qué ocupa la mayor parte de tu mente y tiempo en este preciso momento?",
            de: "Was beschäftigt Ihren Geist und Ihre Zeit in diesem genau Moment am meisten?",
            it: "Cosa occupa la maggior parte della tua mente e del tuo tempo in questo momento esatto?"
        },
        defaultSelected: true
    },
    {
        id: 'family-friends',
        category: { en: 'Family & Friends', fr: 'Amis & Famille', es: 'Familia y Amigos', de: 'Familie & Freunde', it: 'Famiglia e Amici' },
        text: {
            en: "Which relationship or shared moment with a loved one has recently stood out to you?",
            fr: "Quelle relation ou quel moment partagé avec un proche t'a particulièrement marqué ces derniers temps ?",
            es: "¿Qué relación o momento compartido con un ser querido te ha marcado recientemente?",
            de: "Welche Beziehung oder welcher geteilte Moment mit einem geliebten Menschen hat Sie in letzter Zeit besonders berührt?",
            it: "Quale relazione o momento condiviso con una persona cara ti ha colpito particolarmente di recente?"
        },
        defaultSelected: true
    },
    {
        id: 'life-desire',
        category: { en: 'Life & Ambitions', fr: 'Désir de Vie', es: 'Deseos de Vida', de: 'Lebenswünsche', it: 'Desideri di Vita' },
        text: {
            en: "If you could achieve a major project or radically change a habit in the coming months, what would it be?",
            fr: "Si tu pouvais réaliser un grand projet ou changer radicalement une habitude dans les mois à venir, ce serait quoi ?",
            es: "Si pudieras lograr un gran proyecto o cambiar radicalmente un hábito en los próximos meses, ¿cuál sería?",
            de: "Wenn Sie in den kommenden Monaten ein großes Projekt verwirklichen oder eine Gewohnheit radikal ändern könnten, was wäre das?",
            it: "Se potessi realizzare un grande progetto o cambiare radicalmente un'abitudine nei prossimi mesi, quale sarebbe?"
        },
        defaultSelected: true
    },
    {
        id: 'future-learning',
        category: { en: 'Future & Learning', fr: 'Apprentissage Futur', es: 'Futuro y Aprendizaje', de: 'Zukunft & Lernen', it: 'Futuro e Apprendimento' },
        text: {
            en: "What skill or knowledge would you absolutely love to acquire or master in the future?",
            fr: "Quelle compétence ou quelle connaissance aimerais-tu absolument acquérir ou maîtriser dans le futur ?",
            es: "¿Qué habilidad o conocimiento te encantaría adquirir o dominar absolutamente en el futuro?",
            de: "Welche Fähigkeit oder welches Wissen würden Sie in Zukunft unbedingt gerne erwerben oder meistern?",
            it: "Quale abilità o conoscenza ti piacerebbe assolutamente acquisire o padroneggiare in futuro?"
        },
        defaultSelected: true
    },
    {
        id: 'worldwide-situation',
        category: { en: 'Worldview', fr: 'Situation Mondiale', es: 'Situación Mundial', de: 'Weltgeschehen', it: 'Situazione Mondiale' },
        text: {
            en: "What is your current perspective on the state of the world today and its direction?",
            fr: "Quel regard portes-tu sur l'état du monde actuel et son évolution ?",
            es: "¿Cuál es tu perspectiva actual sobre el estado del mundo de hoy y su dirección?",
            de: "Wie blicken Sie auf den Zustand der heutigen Welt und ihre Entwicklung?",
            it: "Qual è la tua attuale prospettiva sullo stato del mondo oggi e sulla sua direzione?"
        },
        defaultSelected: true
    },
    {
        id: 'career-milestone',
        category: { en: 'Career & Projects', fr: 'Carrière & Projets', es: 'Carrera y Proyectos', de: 'Karriere & Projekte', it: 'Carriera e Progetti' },
        text: {
            en: "How do you feel about your current professional trajectory or main creative projects right now?",
            fr: "Comment te sens-tu par rapport à ta trajectoire professionnelle actuelle ou tes principaux projets créatifs ?",
            es: "¿Cómo te sientes acerca de tu actual trayectoria profesional o tus principales proyectos creativos?",
            de: "Wie empfinden Sie Ihre aktuelle berufliche Laufbahn oder Ihre wichtigsten kreativen Projekte?",
            it: "Come ti senti riguardo alla tua attuale traiettoria professionale o ai tuoi principali progetti creativi?"
        },
        defaultSelected: false
    },
    {
        id: 'personal-growth',
        category: { en: 'Personal Growth', fr: 'Évolution Personnelle', es: 'Crecimiento Personal', de: 'Persönliches Wachstum', it: 'Crescita Personale' },
        text: {
            en: "What is the most important personal lesson or realization you have experienced recently?",
            fr: "Quelle est la leçon ou prise de conscience personnelle la plus importante que tu as vécue récemment ?",
            es: "¿Cuál es la lección o toma de conciencia personal más importante que has experimentado recientemente?",
            de: "Was ist die wichtigste persönliche Erkenntnis, die Sie in letzter Zeit gemacht haben?",
            it: "Qual è la lezione o la realizzazione personale più importante che hai vissuto di recente?"
        },
        defaultSelected: false
    },
    {
        id: 'health-energy',
        category: { en: 'Health & Well-being', fr: 'Santé & Énergie', es: 'Salud y Bienestar', de: 'Gesundheit & Wohlbefinden', it: 'Salute e Benessere' },
        text: {
            en: "How are you managing your physical energy, mental balance, and daily well-being right now?",
            fr: "Comment gères-tu ton énergie physique, ton équilibre mental et ton bien-être au quotidien en ce moment ?",
            es: "¿Cómo estás gestionando tu energía física, tu equilibrio mental y tu bienestar diario en este momento?",
            de: "Wie managen Sie im Moment Ihre körperliche Energie, Ihre mentale Balance und Ihr tägliches Wohlbefinden?",
            it: "Come stai gestendo la tua energia fisica, il tuo equilibrio mentale e il tuo benessere quotidiano in questo momento?"
        },
        defaultSelected: false
    },
    {
        id: 'five-year-vision',
        category: { en: 'Vision', fr: 'Vision à 5 ans', es: 'Visión a 5 años', de: '5-Jahres-Vision', it: 'Visione a 5 anni' },
        text: {
            en: "Looking ahead, where do you realistically see yourself living, working, and thriving in 5 years?",
            fr: "En se projetant, où te vois-tu de manière réaliste vivre, travailler et t'épanouir d'ici 5 ans ?",
            es: "Mirando hacia adelante, ¿dónde te ves realistamente viviendo, trabajando y prosperando en 5 años?",
            de: "Wenn Sie nach vorne blicken: Wo sehen Sie sich in 5 Jahren realistischerweise leben, arbeiten und gedeihen?",
            it: "Guardando avanti, dove ti vedi realisticamente a vivere, lavorare e prosperare tra 5 anni?"
        },
        defaultSelected: false
    },
    {
        id: 'gratitude-joy',
        category: { en: 'Gratitude', fr: 'Gratitude & Joie', es: 'Gratitud y Alegría', de: 'Dankbarkeit & Freude', it: 'Gratitudine e Gioia' },
        text: {
            en: "What small or simple things brought you the most joy or gratitude over the past few months?",
            fr: "Quelles petites ou simples choses t'ont apporté le plus de joie ou de gratitude au cours des derniers mois ?",
            es: "¿Qué pequeñas o simples cosas te han traído más alegría o gratitud en los últimos meses?",
            de: "Welche kleinen oder einfachen Dinge haben Ihnen in den letzten Monaten die meiste Freude oder Dankbarkeit gebracht?",
            it: "Quali piccole o semplici cose ti hanno dato più gioia o gratitudine negli ultimi mesi?"
        },
        defaultSelected: false
    }
];

export const TRANSLATIONS = {
    en: {
        appName: "VideoLog",
        manifestoTitle: "Your Personal Time Capsule",
        manifestoText: "Life moves fast. Perspectives shift, ambitions evolve, and memories blur. VideoLog is your private space to pause every 6 months—capturing your raw mindset, your current challenges, and your vision of the world. In a few years, your future self will thank you for preserving who you were today.",
        recordSession: "Record Session",
        recordSubtitle: "Answer your 5 active questions one by one.",
        startRecording: "Start Recording Session",
        importFolder: "Scan / Import from Folder",
        importedCount: "imported successfully!",
        recordedSessions: "Recorded Sessions",
        noSessions: "No videologs recorded yet. Start your first session above or import existing files!",
        play: "Play",
        dashboard: "Dashboard",
        settings: "Settings",
        settingsTitle: "Settings & Question Selection",
        usernameLabel: "Your Name / Username",
        usernameHint: "Used in downloaded video filenames.",
        languageLabel: "Language",
        activeQuestionsLabel: "Active Questions (Max 5)",
        editQuestionsTitle: "Manage Your 5 Active Questions",
        addQuestion: "Add",
        remove: "Remove",
        remindersTitle: "Reminders",
        remindersText: "Download an ICS reminder file for recurring 6-month check-ins.",
        downloadICS: "Download 6-Month Reminder (.ics)",
        cancel: "Dashboard",
        recordAnswer: "Record Answer",
        finishSave: "Finish & Save",
        updateAvailable: "Update Available",
        updateText: "A new version of VideoLog has been released. Refresh now to get the latest features and fixes.",
        later: "Later",
        refreshNow: "Refresh Now",
        installAppTitle: "Install VideoLog",
        installAppText: "Install VideoLog on your device for quick access, offline recording, and a native app experience.",
        installNow: "Install App",
        notNow: "Not Now",
        sessionComplete: "Session complete! All answers recorded and saved locally.",
        onboardingTitle: "Welcome to VideoLog",
        onboardingSubtitle: "Choose up to 5 questions that matter most to you for your time capsule sessions.",
        skipOnboarding: "Skip & Use Default (5)",
        saveOnboarding: "Save & Start Using VideoLog",
        selectedCount: "Selected"
    },
    fr: {
        appName: "VideoLog",
        manifestoTitle: "Votre Capsule Temporelle Personnelle",
        manifestoText: "La vie va vite. Les perspectives changent, les ambitions évoluent et les souvenirs s'estompent. VideoLog est votre espace privé pour faire une pause tous les 6 mois : capturez votre état d'esprit brut, vos défis actuels et votre vision du monde. Dans quelques ans, votre futur vous remerciera d'avoir préservé qui vous étiez aujourd'hui.",
        recordSession: "Enregistrer une session",
        recordSubtitle: "Répondez à vos 5 questions actives une par une.",
        startRecording: "Démarrer la session d'enregistrement",
        importFolder: "Scanner / Importer un dossier",
        importedCount: "importés avec succès !",
        recordedSessions: "Sessions enregistrées",
        noSessions: "Aucun videolog pour l'instant. Démarrez votre première session ci-dessus ou importez des fichiers existants !",
        play: "Lire",
        dashboard: "Tableau de bord",
        settings: "Paramètres",
        settingsTitle: "Paramètres & Sélection des questions",
        usernameLabel: "Votre Nom / Pseudo",
        usernameHint: "Utilisé dans les noms de fichiers vidéo téléchargés.",
        languageLabel: "Langue",
        activeQuestionsLabel: "Questions Actives (Max 5)",
        editQuestionsTitle: "Gérer vos 5 questions actives",
        addQuestion: "Ajouter",
        remove: "Retirer",
        remindersTitle: "Rappels",
        remindersText: "Téléchargez un fichier ICS pour configurer un rappel récurrent tous les 6 mois.",
        downloadICS: "Télécharger le rappel 6 mois (.ics)",
        cancel: "Tableau de bord",
        recordAnswer: "Enregistrer la réponse",
        finishSave: "Terminer & Sauvegarder",
        updateAvailable: "Mise à jour disponible",
        updateText: "Une nouvelle version de VideoLog est sortie. Actualisez pour obtenir les dernières fonctionnalités.",
        later: "Plus tard",
        refreshNow: "Actualiser",
        installAppTitle: "Installer VideoLog",
        installAppText: "Installez VideoLog sur votre appareil pour un accès rapide, un enregistrement hors-ligne et une expérience native.",
        installNow: "Installer",
        notNow: "Pas maintenant",
        sessionComplete: "Session terminée ! Toutes les réponses ont été enregistrées localement.",
        onboardingTitle: "Bienvenue sur VideoLog",
        onboardingSubtitle: "Choisissez jusqu'à 5 questions qui comptent le plus pour vous lors de vos sessions de capsule temporelle.",
        skipOnboarding: "Passer (utiliser les 5 par défaut)",
        saveOnboarding: "Enregistrer & Démarrer",
        selectedCount: "Sélectionnées"
    },
    es: {
        appName: "VideoLog",
        manifestoTitle: "Tu Cápsula del Tiempo Personal",
        manifestoText: "La vida pasa rápido. Las perspectivas cambian, las ambiciones evolucionan y los recuerdos se desvanecen. VideoLog es tu espacio privado para hacer una pausa cada 6 meses: captura tu mentalidad sin filtros, tus desafíos actuales y tu visión del mundo. En unos años, tu ‘yo’ del futuro te agradecerá por preservar quién eras hoy.",
        recordSession: "Grabar sesión",
        recordSubtitle: "Responde tus 5 preguntas activas una por una.",
        startRecording: "Iniciar sesión de grabación",
        importFolder: "Escanear / Importar carpeta",
        importedCount: "importados con éxito!",
        recordedSessions: "Sesiones grabadas",
        noSessions: "Aún no hay videologs grabados. ¡Comienza tu primera sesión arriba o importa archivos existentes!",
        play: "Reproducir",
        dashboard: "Panel",
        settings: "Ajustes",
        settingsTitle: "Ajustes y Selección de Preguntas",
        usernameLabel: "Tu Nombre / Usuario",
        usernameHint: "Usado en los nombres de archivos de video descargados.",
        languageLabel: "Idioma",
        activeQuestionsLabel: "Preguntas Activas (Max 5)",
        editQuestionsTitle: "Gestionar tus 5 preguntas activas",
        addQuestion: "Añadir",
        remove: "Quitar",
        remindersTitle: "Recordatorios",
        remindersText: "Descarga un archivo ICS para configurar un recordatorio recurrente cada 6 meses.",
        downloadICS: "Descargar recordatorio de 6 meses (.ics)",
        cancel: "Panel",
        recordAnswer: "Grabar Respuesta",
        finishSave: "Terminar y Guardar",
        updateAvailable: "Actualización Disponible",
        updateText: "Se ha lanzado una nueva versión de VideoLog. Actualiza ahora para obtener las últimas mejoras.",
        later: "Más tarde",
        refreshNow: "Actualizar",
        installAppTitle: "Instalar VideoLog",
        installAppText: "Instala VideoLog en tu dispositivo para un acceso rápido, grabación offline y experiencia nativa.",
        installNow: "Instalar App",
        notNow: "Ahora no",
        sessionComplete: "¡Sesión completa! Todas las respuestas grabadas y guardadas localmente.",
        onboardingTitle: "Bienvenido a VideoLog",
        onboardingSubtitle: "Elige hasta 5 preguntas que más te importen para tus sesiones de cápsula del tiempo.",
        skipOnboarding: "Omitir (usar 5 por defecto)",
        saveOnboarding: "Guardar y Empezar",
        selectedCount: "Seleccionadas"
    },
    de: {
        appName: "VideoLog",
        manifestoTitle: "Ihre persönliche Zeitkapsel",
        manifestoText: "Das Leben vergeht schnell. Perspektiven verschieben sich, Ambitionen entwickeln sich weiter und Erinnerungen verblassen. VideoLog ist Ihr privater Ort, um alle 6 Monate Innehaltet zu halten – halten Sie Ihre rohe Denkweise, Ihre aktuellen Herausforderungen und Ihre Vision der Welt fest. In ein paar Jahren wird Ihr zukünftiges Ich es Ihnen danken.",
        recordSession: "Aufnahmesitzung starten",
        recordSubtitle: "Beantworten Sie Ihre 5 aktiven Fragen nacheinander.",
        startRecording: "Aufnahme starten",
        importFolder: "Ordner scannen / importieren",
        importedCount: "erfolgreich importiert!",
        recordedSessions: "Aufgezeichnete Sitzungen",
        noSessions: "Noch keine VideoLogs vorhanden. Starten Sie Ihre erste Sitzung oben oder importieren Sie vorhandene Dateien!",
        play: "Abspielen",
        dashboard: "Übersicht",
        settings: "Einstellungen",
        settingsTitle: "Einstellungen & Fragenauswahl",
        usernameLabel: "Ihr Name / Benutzername",
        usernameHint: "Wird für heruntergeladene Videodateinamen verwendet.",
        languageLabel: "Sprache",
        activeQuestionsLabel: "Aktive Fragen (Max 5)",
        editQuestionsTitle: "Verwalten Sie Ihre 5 aktiven Fragen",
        addQuestion: "Hinzufügen",
        remove: "Entfernen",
        remindersTitle: "Erinnerungen",
        remindersText: "Laden Sie eine ICS-Datei für wiederkehrende 6-Monats-Erinnerungen herunter.",
        downloadICS: "6-Monats-Erinnerung herunterladen (.ics)",
        cancel: "Übersicht",
        recordAnswer: "Antwort aufnehmen",
        finishSave: "Beenden & Speichern",
        updateAvailable: "Update verfügbar",
        updateText: "Eine neue Version von VideoLog ist verfügbar. Aktualisieren Sie jetzt.",
        later: "Später",
        refreshNow: "Jetzt aktualisieren",
        installAppTitle: "VideoLog installieren",
        installAppText: "Installieren Sie VideoLog für schnellen Zugriff, Offline-Aufnahme und ein natives App-Erlebnis.",
        installNow: "App installieren",
        notNow: "Später",
        sessionComplete: "Sitzung abgeschlossen! Alle Antworten lokal gespeichert.",
        onboardingTitle: "Willkommen bei VideoLog",
        onboardingSubtitle: "Wählen Sie bis zu 5 Fragen aus, die Ihnen für Ihre Zeitkapsel-Sitzungen am wichtigsten sind.",
        skipOnboarding: "Überspringen (Standard 5 verwenden)",
        saveOnboarding: "Speichern & Starten",
        selectedCount: "Ausgewählt"
    },
    it: {
        appName: "VideoLog",
        manifestoTitle: "La tua Capsula del Tempo Personale",
        manifestoText: "La vita scorre veloce. Le prospettive cambiano, le ambizioni evolvono e i ricordi sfumano. VideoLog è il tuo spazio privato per fermarti ogni 6 mesi: cattura la tua mentalità autentica, le tue sfide attuali e la tua visione del mondo. Tra qualche anno, il tuo io futuro ti ringrazierà per aver preservato chi eri oggi.",
        recordSession: "Avvia sessione di registrazione",
        recordSubtitle: "Rispondi alle tue 5 domande attive una per una.",
        startRecording: "Avvia registrazione",
        importFolder: "Scansiona / Importa cartella",
        importedCount: "importati con successo!",
        recordedSessions: "Sessioni registrate",
        noSessions: "Nessun videolog registrato. Inizia la tua prima sessione qui sopra o importa file esistenti!",
        play: "Riproduci",
        dashboard: "Dashboard",
        settings: "Impostazioni",
        settingsTitle: "Impostazioni e Selezione Domande",
        usernameLabel: "Il tuo Nome / Username",
        usernameHint: "Utilizzato nei nomi dei file video scaricati.",
        languageLabel: "Lingua",
        activeQuestionsLabel: "Domande Attive (Max 5)",
        editQuestionsTitle: "Gestisci le tue 5 domande attive",
        addQuestion: "Aggiungi",
        remove: "Rimuovi",
        remindersTitle: "Promemoria",
        remindersText: "Scarica un file ICS per impostare un promemoria ricorrente ogni 6 mesi.",
        downloadICS: "Scarica Promemoria 6 Mesi (.ics)",
        cancel: "Dashboard",
        recordAnswer: "Registra Risposta",
        finishSave: "Termina e Salva",
        updateAvailable: "Aggiornamento Disponibile",
        updateText: "È stata rilasciata una nuova versione di VideoLog. Aggiorna ora per le ultime novità.",
        later: "Più tardi",
        refreshNow: "Aggiorna Ora",
        installAppTitle: "Installa VideoLog",
        installAppText: "Installa VideoLog sul tuo dispositivo per un accesso rapido, registrazione offline ed esperienza nativa.",
        installNow: "Installa App",
        notNow: "Non ora",
        sessionComplete: "Sessione completata! Tutte le risposte registrate e salvate localmente.",
        onboardingTitle: "Benvenuto su VideoLog",
        onboardingSubtitle: "Scegli fino a 5 domande che contano di più per te per le tue sessioni di capsula del tempo.",
        skipOnboarding: "Salta (usa le 5 di default)",
        saveOnboarding: "Salva e Inizia",
        selectedCount: "Selezionate"
    }
};
