export const TRANSLATIONS = {
    en: {
        appName: "VideoLog",
        manifestoTitle: "Your Personal Time Capsule",
        manifestoText: "Life moves fast. Perspectives shift, ambitions evolve, and memories blur. VideoLog is your private space to pause every 6 months—capturing your raw mindset, your current challenges, and your vision of the world. In a few years, your future self will thank you for preserving who you were today.",
        recordSession: "Record Session",
        recordSubtitle: "Answer your active pack questions one by one.",
        startRecording: "Start Recording Session",
        recordedSessions: "Recorded Sessions",
        noSessions: "No videologs recorded yet. Start your first session above!",
        play: "Play",
        dashboard: "Dashboard",
        settings: "Settings",
        settingsTitle: "Settings & Question Packs",
        usernameLabel: "Your Name / Username",
        usernameHint: "Used in downloaded video filenames.",
        languageLabel: "Language",
        activePackLabel: "Active Question Pack",
        editQuestionsTitle: "Edit Questions in Pack",
        addQuestion: "Add Question",
        delete: "Delete",
        remindersTitle: "Reminders",
        remindersText: "Download an ICS reminder file for recurring 6-month check-ins.",
        downloadICS: "Download 6-Month Reminder (.ics)",
        cancel: "Dashboard",
        recordAnswer: "Record Answer",
        finishSave: "Finish & Save",
        updateAvailable: "Update Available",
        updateText: "A new version of VideoLog has been released. Refresh now to get the latest features and fixes.",
        later: "Later",
        refreshNow: "Refresh Now",
        installAppTitle: "Install VideoLog",
        installAppText: "Install VideoLog on your device for quick access, offline recording, and a native app experience.",
        installNow: "Install App",
        notNow: "Not Now",
        sessionComplete: "Session complete! All answers recorded and saved locally."
    },
    fr: {
        appName: "VideoLog",
        manifestoTitle: "Votre Capsule Temporelle Personnelle",
        manifestoText: "La vie va vite. Les perspectives changent, les ambitions évoluent et les souvenirs s'estompent. VideoLog est votre espace privé pour faire une pause tous les 6 mois : capturez votre état d'esprit brut, vos défis actuels et votre vision du monde. Dans quelques ans, votre futur vous remerciera d'avoir préservé qui vous étiez aujourd'hui.",
        recordSession: "Enregistrer une session",
        recordSubtitle: "Répondez aux questions de votre pack actif une par une.",
        startRecording: "Démarrer la session d'enregistrement",
        recordedSessions: "Sessions enregistrées",
        noSessions: "Aucun videolog pour l'instant. Démarrez votre première session ci-dessus !",
        play: "Lire",
        dashboard: "Tableau de bord",
        settings: "Paramètres",
        settingsTitle: "Paramètres & Packs de questions",
        usernameLabel: "Votre Nom / Pseudo",
        usernameHint: "Utilisé dans les noms de fichiers vidéo téléchargés.",
        languageLabel: "Langue",
        activePackLabel: "Pack de questions actif",
        editQuestionsTitle: "Modifier les questions du pack",
        addQuestion: "Ajouter une question",
        delete: "Supprimer",
        remindersTitle: "Rappels",
        remindersText: "Téléchargez un fichier ICS pour configurer un rappel récurrent tous les 6 mois.",
        downloadICS: "Télécharger le rappel 6 mois (.ics)",
        cancel: "Tableau de bord",
        recordAnswer: "Enregistrer la réponse",
        finishSave: "Terminer & Sauvegarder",
        updateAvailable: "Mise à jour disponible",
        updateText: "Une nouvelle version de VideoLog est sortie. Actualisez pour obtenir les dernières fonctionnalités.",
        later: "Plus tard",
        refreshNow: "Actualiser",
        installAppTitle: "Installer VideoLog",
        installAppText: "Installez VideoLog sur votre appareil pour un accès rapide, un enregistrement hors-ligne et une expérience native.",
        installNow: "Installer",
        notNow: "Pas maintenant",
        sessionComplete: "Session terminée ! Toutes les réponses ont été enregistrées localement."
    },
    es: {
        appName: "VideoLog",
        manifestoTitle: "Tu Cápsula del Tiempo Personal",
        manifestoText: "La vida pasa rápido. Las perspectivas cambian, las ambiciones evolucionan y los recuerdos se desvanecen. VideoLog es tu espacio privado para hacer una pausa cada 6 meses: captura tu mentalidad sin filtros, tus desafíos actuales y tu visión del mundo. En unos años, tu ‘yo’ del futuro te agradecerá por preservar quién eras hoy.",
        recordSession: "Grabar sesión",
        recordSubtitle: "Responde las preguntas de tu pack activo una por una.",
        startRecording: "Iniciar sesión de grabación",
        recordedSessions: "Sesiones grabadas",
        noSessions: "Aún no hay videologs grabados. ¡Comienza tu primera sesión arriba!",
        play: "Reproducir",
        dashboard: "Panel",
        settings: "Ajustes",
        settingsTitle: "Ajustes y Packs de Preguntas",
        usernameLabel: "Tu Nombre / Usuario",
        usernameHint: "Usado en los nombres de archivos de video descargados.",
        languageLabel: "Idioma",
        activePackLabel: "Pack de Preguntas Activo",
        editQuestionsTitle: "Editar Preguntas del Pack",
        addQuestion: "Añadir Pregunta",
        delete: "Eliminar",
        remindersTitle: "Recordatorios",
        remindersText: "Descarga un archivo ICS para configurar un recordatorio recurrente cada 6 meses.",
        downloadICS: "Descargar recordatorio de 6 meses (.ics)",
        cancel: "Panel",
        recordAnswer: "Grabar Respuesta",
        finishSave: "Terminar y Guardar",
        updateAvailable: "Actualización Disponible",
        updateText: "Se ha lanzado una nueva versión de VideoLog. Actualiza ahora para obtener las últimas mejoras.",
        later: "Más tarde",
        refreshNow: "Actualizar",
        installAppTitle: "Instalar VideoLog",
        installAppText: "Instala VideoLog en tu dispositivo para un acceso rápido, grabación offline y experiencia nativa.",
        installNow: "Instalar App",
        notNow: "Ahora no",
        sessionComplete: "¡Sesión completa! Todas las respuestas grabadas y guardadas localmente."
    },
    de: {
        appName: "VideoLog",
        manifestoTitle: "Ihre persönliche Zeitkapsel",
        manifestoText: "Das Leben vergeht schnell. Perspektiven verschieben sich, Ambitionen entwickeln sich weiter und Erinnerungen verblassen. VideoLog ist Ihr privater Ort, um alle 6 Monate Innehaltet zu halten – halten Sie Ihre rohe Denkweise, Ihre aktuellen Herausforderungen und Ihre Vision der Welt fest. In ein paar Jahren wird Ihr zukünftiges Ich es Ihnen danken.",
        recordSession: "Aufnahmesitzung starten",
        recordSubtitle: "Beantworten Sie die Fragen Ihres aktiven Pakets nacheinander.",
        startRecording: "Aufnahme starten",
        recordedSessions: "Aufgezeichnete Sitzungen",
        noSessions: "Noch keine VideoLogs vorhanden. Starten Sie Ihre erste Sitzung oben!",
        play: "Abspielen",
        dashboard: "Übersicht",
        settings: "Einstellungen",
        settingsTitle: "Einstellungen & Fragen-Pakete",
        usernameLabel: "Ihr Name / Benutzername",
        usernameHint: "Wird für heruntergeladene Videodateinamen verwendet.",
        languageLabel: "Sprache",
        activePackLabel: "Aktives Fragen-Paket",
        editQuestionsTitle: "Fragen bearbeiten",
        addQuestion: "Frage hinzufügen",
        delete: "Löschen",
        remindersTitle: "Erinnerungen",
        remindersText: "Laden Sie eine ICS-Datei für wiederkehrende 6-Monats-Erinnerungen herunter.",
        downloadICS: "6-Monats-Erinnerung herunterladen (.ics)",
        cancel: "Übersicht",
        recordAnswer: "Antwort aufnehmen",
        finishSave: "Beenden & Speichern",
        updateAvailable: "Update verfügbar",
        updateText: "Eine neue Version von VideoLog ist verfügbar. Aktualisieren Sie jetzt.",
        later: "Später",
        refreshNow: "Jetzt aktualisieren",
        installAppTitle: "VideoLog installieren",
        installAppText: "Installieren Sie VideoLog für schnellen Zugriff, Offline-Aufnahme und ein natives App-Erlebnis.",
        installNow: "App installieren",
        notNow: "Später",
        sessionComplete: "Sitzung abgeschlossen! Alle Antworten lokal gespeichert."
    },
    it: {
        appName: "VideoLog",
        manifestoTitle: "La tua Capsula del Tempo Personale",
        manifestoText: "La vita scorre veloce. Le prospettive cambiano, le ambizioni evolvono e i ricordi sfumano. VideoLog è il tuo spazio privato per fermarti ogni 6 mesi: cattura la tua mentalità autentica, le tue sfide attuali e la tua visione del mondo. Tra qualche anno, il tuo io futuro ti ringrazierà per aver preservato chi eri oggi.",
        recordSession: "Avvia sessione di registrazione",
        recordSubtitle: "Rispondi alle domande del tuo pacchetto attivo una per una.",
        startRecording: "Avvia registrazione",
        recordedSessions: "Sessioni registrate",
        noSessions: "Nessun videolog registrato. Inizia la tua prima sessione qui sopra!",
        play: "Riproduci",
        dashboard: "Dashboard",
        settings: "Impostazioni",
        settingsTitle: "Impostazioni e Pacchetti di Domande",
        usernameLabel: "Il tuo Nome / Username",
        usernameHint: "Utilizzato nei nomi dei file video scaricati.",
        languageLabel: "Lingua",
        activePackLabel: "Pacchetto Attivo",
        editQuestionsTitle: "Modifica Domande del Pacchetto",
        addQuestion: "Aggiungi Domanda",
        delete: "Elimina",
        remindersTitle: "Promemoria",
        remindersText: "Scarica un file ICS per impostare un promemoria ricorrente ogni 6 mesi.",
        downloadICS: "Scarica Promemoria 6 Mesi (.ics)",
        cancel: "Dashboard",
        recordAnswer: "Registra Risposta",
        finishSave: "Termina e Salva",
        updateAvailable: "Aggiornamento Disponibile",
        updateText: "È stata rilasciata una nuova versione di VideoLog. Aggiorna ora per le ultime novità.",
        later: "Più tardi",
        refreshNow: "Aggiorna Ora",
        installAppTitle: "Installa VideoLog",
        installAppText: "Installa VideoLog sul tuo dispositivo per un accesso rapido, registrazione offline ed esperienza nativa.",
        installNow: "Installa App",
        notNow: "Non ora",
        sessionComplete: "Sessione completata! Tutte le risposte registrate e salvate localmente."
    }
};

export const QUESTION_PACKS = {
    'young-adult': {
        name: { en: 'Young Adult (20s - 30s)', fr: 'Jeune Adulte (20 - 30 ans)', es: 'Joven Adulto (20s - 30s)', de: 'Jnger Erwachsener (20er - 30er)', it: 'Giovane Adulto (20 - 30 anni)' },
        description: { en: 'Focus on career foundations, independence, worldview, and personal discovery.', fr: 'Focus sur les bases de carrière, l\'indépendance et la découverte personnelle.', es: 'Enfoque en carrera, independencia y descubrimiento personal.', de: 'Fokus auf Karriere, Unabhängigkeit und Selbstfindung.', it: 'Focus su carriera, indipendenza e scoperta personale.' },
        questions: [
            { id: 'ya-career', category: { en: 'Career & Ambitions', fr: 'Carrière & Ambitions', es: 'Carrera y Ambiciones', de: 'Karriere & Ambitionen', it: 'Carriera e Ambizioni' }, text: { en: 'What is your current main occupation or project, and how do you feel about your career trajectory right now?', fr: 'Quelle est votre occupation ou projet principal actuel, et que pensez-vous de votre trajectoire professionnelle ?', es: '¿Cuál es tu ocupación o proyecto principal actual y cómo te sientes respecto a tu trayectoria profesional?', de: 'Was ist Ihre aktuelle Hauptbeschäftigung und wie empfinden Sie Ihre Karriere?', it: 'Qual è la tua attuale occupazione o progetto principale e come ti senti riguardo alla tua traiettoria professionale?' } },
            { id: 'ya-world', category: { en: 'Worldview', fr: 'Vision du Monde', es: 'Visión del Mundo', de: 'Weltbild', it: 'Visione del Mondo' }, text: { en: 'What major world event or societal trend occupies your mind the most today?', fr: 'Quel événement mondial ou tendance de société occupe le plus votre esprit aujourd\'hui ?', es: '¿Qué evento mundial o tendencia social ocupa más tu mente hoy?', de: 'Welches weltweite Ereignis oder welcher gesellschaftliche Trend beschäftigt Sie heute am meisten?', it: 'Quale grande evento mondiale o tendenza sociale occupa di più la tua mente oggi?' } },
            { id: 'ya-family', category: { en: 'Family & Relations', fr: 'Famille & Relations', es: 'Familia y Relaciones', de: 'Familie & Beziehungen', it: 'Famiglia e Relazioni' }, text: { en: 'How has your relationship with your family and close friends evolved over the past 6 months?', fr: 'Comment votre relation avec votre famille et vos proches a-t-elle évolué au cours des 6 derniers mois ?', es: '¿Cómo ha evolucionado tu relación con tu familia y amigos cercanos en los últimos 6 meses?', de: 'Wie hat sich Ihre Beziehung zu Familie und engen Freunden in den letzten 6 Monaten entwickelt?', it: 'Come si è evoluta la tua relazione con la famiglia e gli amici stretti negli ultimi 6 mesi?' } },
            { id: 'ya-lessons', category: { en: 'Personal Growth', fr: 'Évolution Personnelle', es: 'Crecimiento Personal', de: 'Persönliches Wachstum', it: 'Crescita Personale' }, text: { en: 'What is the most important personal lesson or realization you have experienced recently?', fr: 'Quelle est la leçon ou prise de conscience personnelle la plus importante que vous avez vécue récemment ?', es: '¿Cuál es la lección o toma de conciencia personal más importante que has experimentado recientemente?', de: 'Was ist die wichtigste persönliche Erkenntnis, die Sie kürzlich gemacht haben?', it: 'Qual è la lezione o la realizzazione personale più importante che hai vissuto di recente?' } },
            { id: 'ya-future', category: { en: 'Vision', fr: 'Vision', es: 'Visión', de: 'Vision', it: 'Visione' }, text: { en: 'Where do you realistically see yourself living and working in 2 years?', fr: 'Où vous voyez-vous de manière réaliste vivre et travailler dans 2 ans ?', es: '¿Dónde te ves realisticamente viviendo y trabajando en 2 años?', de: 'Wo sehen Sie sich in 2 Jahren realistischerweise leben und arbeiten?', it: 'Dove ti vedi realisticamente a vivere e lavorare tra 2 anni?' } }
        ]
    },
    'adult': {
        name: { en: 'Adult & Established (30s+)', fr: 'Adulte & Établi (30 ans+)', es: 'Adulto y Establecido (30s+)', de: 'Erwachsen & Etabliert (30+)', it: 'Adulto e Stabilito (30+)' },
        description: { en: 'Focus on life balance, long-term vision, family transmission, and deep projects.', fr: 'Focus sur l\'équilibre de vie, la vision à long terme et la transmission familiale.', es: 'Enfoque en equilibrio de vida, visión a largo plazo y proyectos.', de: 'Fokus auf Lebensbalance, langfristige Vision und Projekte.', it: 'Focus su equilibrio di vita, visione a lungo termine e progetti.' },
        questions: [
            { id: 'ad-career', category: { en: 'Career & Ambitions', fr: 'Carrière & Ambitions', es: 'Carrera y Ambiciones', de: 'Karriere & Ambitionen', it: 'Carriera e Ambizioni' }, text: { en: 'How would you summarize your current professional life, major responsibilities, and main frustrations or prides?', fr: 'Comment résumeriez-vous votre vie professionnelle actuelle, vos responsabilités et vos fiertés/frustrations ?', es: '¿Cómo resumirías tu vida profesional actual, responsabilidades principales y mayores orgullos o frustraciones?', de: 'Wie würden Sie Ihr aktuelles Berufsleben und Ihre größten Stolzpunkte oder Frustrationen zusammenfassen?', it: 'Come riassumeresti la tua vita professionale attuale, le tue principali responsabilità e i tuoi orgogli o frustrazioni?' } },
            { id: 'ad-society', category: { en: 'Worldview', fr: 'Vision du Monde', es: 'Visión del Mundo', de: 'Weltbild', it: 'Visione del Mondo' }, text: { en: 'What is your current perspective on society, technology (like AI), and the direction things are heading?', fr: 'Quelle est votre perspective actuelle sur la société, la technologie (IA) et la direction que prennent les choses ?', es: '¿Cuál es tu perspectiva actual sobre la sociedad, la tecnología (como la IA) y hacia dónde van las cosas?', de: 'Was ist Ihre aktuelle Perspektive auf Gesellschaft, Technologie (wie KI) und die Richtung, in die sich die Dinge entwickeln?', it: 'Qual è la tua attuale prospettiva sulla società, la tecnologia (come l\'IA) e la direzione in cui stanno andando le cose?' } },
            { id: 'ad-family', category: { en: 'Family & Transmission', fr: 'Famille & Transmission', es: 'Familia y Transmisión', de: 'Familie & Vermächtnis', it: 'Famiglia e Trasmissione' }, text: { en: 'What are you trying to transmit or teach to your children or close family members at this stage of their lives?', fr: 'Que essayez-vous de transmettre ou d\'enseigner à vos enfants ou proches à cette étape de leur vie ?', es: '¿Qué estás tratando de transmitir o enseñar a tus hijos o familiares cercanos en esta etapa?', de: 'Was versuchen Sie Ihren Kindern oder nahen Familienmitgliedern in dieser Lebensphase zu vermitteln?', it: 'Cosa stai cercando di trasmettere o insegnare ai tuoi figli o familiari stretti in questa fase della loro vita?' } },
            { id: 'ad-projects', category: { en: 'Personal Projects', fr: 'Projets Personnels', es: 'Proyectos Personales', de: 'Persönliche Projekte', it: 'Progetti Personali' }, text: { en: 'What passion projects, hobbies, or personal experiments are keeping you energized right now?', fr: 'Quels projets de passion, loisirs ou expériences personnelles vous dynamisent en ce moment ?', es: '¿Qué proyectos de pasión, pasatiempos o experimentos personales te mantienen con energía ahora mismo?', de: 'Welche Leidenschaftsprojekte oder Hobbys geben Ihnen im Moment Energie?', it: 'Quali progetti di passione, hobby o esperimenti personali ti danno energia in questo momento?' } },
            { id: 'ad-future', category: { en: 'Capsule & Vision', fr: 'Capsule & Vision', es: 'Cápsula y Visión', de: 'Kapsel & Vision', it: 'Capsula e Visione' }, text: { en: 'If you could give one piece of advice to your future self looking back 5 years from now, what would it be?', fr: 'Si vous pouviez donner un conseil à votre futur vous dans 5 ans, quel serait-il ?', es: 'Si pudieras darle un consejo a tu ' + 'yo' + ' del futuro mirando atrás en 5 años, ¿cuál sería?', de: 'Wenn Sie Ihrem zukünftigen Ich in 5 Jahren einen Rat geben könnten, welcher wäre das?', it: 'Se potessi dare un consiglio al tuo te stesso futuro tra 5 anni, quale sarebbe?' } }
        ]
    },
    'young-person': {
        name: { en: 'Young Person / Student', fr: 'Jeune / Étudiant', es: 'Joven / Estudiante', de: 'Jugendlicher / Student', it: 'Giovane / Studente' },
        description: { en: 'Focus on studies, curiosities, friendships, and future dreams.', fr: 'Focus sur les études, curiosités, amitiés et rêves futurs.', es: 'Enfoque en estudios, curiosidades, amistades y sueños futuros.', de: 'Fokus auf Studium, Neugier, Freundschaften und Träume.', it: 'Focus su studi, curiosità, amicizie e sogni futuri.' },
        questions: [
            { id: 'yp-studies', category: { en: 'Studies & Work', fr: 'Études & Travail', es: 'Estudios y Trabajo', de: 'Studium & Arbeit', it: 'Studi e Lavoro' }, text: { en: 'What are you studying or working on right now, and what do you enjoy most about it?', fr: 'Qu\'étudiez-vous ou sur quoi travaillez-vous en ce moment, et qu\'aimez-vous le plus ?', es: '¿Qué estás estudiando o en qué trabajas ahora, y qué es lo que más te gusta?', de: 'Was studieren oder arbeiten Sie gerade und was gefällt Ihnen daran am meisten?', it: 'Cosa stai studiando o su cui stai lavorando ora e cosa ti piace di più?' } },
            { id: 'yp-friends', category: { en: 'Friendships', fr: 'Amitiés', es: 'Amistades', de: 'Freundschaften', it: 'Amicizie' }, text: { en: 'Who are your closest friends, and what activities do you love doing together?', fr: 'Qui sont vos amis les plus proches, et quelles activités aimez-vous faire ensemble ?', es: '¿Quiénes son tus amigos más cercanos y qué actividades te encanta hacer juntos?', de: 'Wer sind Ihre besten Freunde und was machen Sie gerne zusammen?', it: 'Chi sono i tuoi amici più stretti e quali attività ami fare insieme?' } },
            { id: 'yp-curiosity', category: { en: 'Learning', fr: 'Apprentissage', es: 'Aprendizaje', de: 'Lernen', it: 'Apprendimento' }, text: { en: 'What skill or subject are you most curious about learning in the near future?', fr: 'Quelle compétence ou matière avez-vous le plus hâte d\'apprendre prochainement ?', es: '¿Qué habilidad o materia tienes más curiosidad por aprender pronto?', de: 'Welche Fähigkeit möchten Sie in naher Zukunft am liebsten lernen?', it: 'Quale abilità o materia sei più curioso di imparare nel prossimo futuro?' } },
            { id: 'yp-pride', category: { en: 'Achievements', fr: 'Réalisations', es: 'Logros', de: 'Erfolge', it: 'Traguardi' }, text: { en: 'What is something you are proud of achieving or discovering over the last 6 months?', fr: 'De quoi êtes-vous fier d\'avoir accompli ou découvert ces 6 derniers mois ?', es: '¿De qué estás orgulloso de haber logrado o descubierto en los últimos 6 meses?', de: 'Worauf sind Sie stolz, was Sie in den letzten 6 Monaten erreicht haben?', it: 'Di cosa sei orgoglioso di aver raggiunto o scoperto negli ultimi 6 mesi?' } },
            { id: 'yp-future', category: { en: 'Future Dreams', fr: 'Rêves Futurs', es: 'Sueños Futuros', de: 'Zukunftsträume', it: 'Sogni Futuri' }, text: { en: 'What do you hope to be doing 5 years from now?', fr: 'Que espérez-vous faire d\'ici 5 ans ?', es: '¿Qué esperas estar haciendo dentro de 5 años?', de: 'Was hoffen Sie, in 5 Jahren zu tun?', it: 'Cosa speri di fare da qui a 5 anni?' } }
        ]
    }
};
